backend:
  name: github # Refer to https://www.netlifycms.org/docs/authentication-backends/ for auth backend list and instructions
  branch: production # Branch to update
  repo: jasoderstrom/justinsoderstrom.com # Repo for pushing new commits. Make sure to replace with your repo!
  publish_mode: editorial_workflow # Enables the editorial workflow

media_library:
  name: cloudinary
  config:
    cloud_name: justinsoderstrom 
    api_key: 616713912117222
    username: justin@justinsoderstrom.com
public_folder: assets

collections:
  - name: blog
    label: "Post"
    folder: "content"
    create: true
    slug: "{{month}}-{{day}}-{{year}}-{{slug}}.md"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Cover Image", name: "cover", widget: "image"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
